version: '3'

services:
  web:
    image: nginx
    hostname: registry.koshelev.site
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nexus.conf:/etc/nginx/conf.d/nexus.conf
      - ./nginx/logs/:/var/log/nginx/
      - ./tls/:/tls/
    ports:
      - "80:80"
      - "443:443"
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    volumes:
      - "./data/nexus:/nexus-data"
